// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8nkGiRvUaCdCt4ys5hcbBTXAx-yOukJM',
    appId: '1:774877648388:web:30b9a87cd776638239c751',
    messagingSenderId: '774877648388',
    projectId: 'tubes-market-hewan',
    authDomain: 'tubes-market-hewan.firebaseapp.com',
    storageBucket: 'tubes-market-hewan.appspot.com',
    measurementId: 'G-ZLKJ1VL76G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG2KCH2laN3kfe9POfhGLyUPPu8fvAky0',
    appId: '1:774877648388:android:58d774cacd38c24539c751',
    messagingSenderId: '774877648388',
    projectId: 'tubes-market-hewan',
    storageBucket: 'tubes-market-hewan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs2j2lUKV9rkJDUDO0mbGOU96690g1ZME',
    appId: '1:774877648388:ios:e02752fb125a4ec439c751',
    messagingSenderId: '774877648388',
    projectId: 'tubes-market-hewan',
    storageBucket: 'tubes-market-hewan.appspot.com',
    iosBundleId: 'com.example.tubesMarketHewan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs2j2lUKV9rkJDUDO0mbGOU96690g1ZME',
    appId: '1:774877648388:ios:bad5c791296319d539c751',
    messagingSenderId: '774877648388',
    projectId: 'tubes-market-hewan',
    storageBucket: 'tubes-market-hewan.appspot.com',
    iosBundleId: 'com.example.tubesMarketHewan.RunnerTests',
  );
}
